
[package]
name = "user_programs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "simple_test"
test = false
bench = false
path = "src/simple_test.rs"

[dependencies]
tinyos_userlib = { path = "../tinyos_userlib" }

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]